### ISSUE TITLE
`pointer` into `dgCMatrix`

### ISSUE THREAD

**Issue by Yunuuuu** [LTLA/scran.chan#11]
Is it possible to turn the cpp pointer back into R?

Now `logNormCounts.chan` return a `pointer` contaning the logcounts matrix, which makes it hard to integrate with `Seurat` or `SingleCellExperiment`. I have made a [package](https://github.com/Yunuuuu/fscran) to bring `scran.chan` for both `Seurat` and `SingleCellExperiment` objects, however, the current implementation of the `logNormCounts.chan` function made it hard in the integration process (I cannot bring the log counts matrix into the `Seurat` or `SingleCellExperiment` object).

**Comment by LTLA** [comment]
Currently, this is not easily done, I'm afraid.

Perhaps you might have a look at how [**scranpy**](https://github.com/biocpy/scranpy) handles this problem. Once we have the same system in **scran.chan**, we could just pass `DelayedMatrix` objects to `logNormCounts.chan`, and this would return back a new `DelayedArray` that would be easily insertable into the assays of an SCE.

I hope to finish cleaning up all the C++ code so that we can have **scran.chan** in Bioconductor by the next release. In the meantime, you might consider just implementing the same approach as **scranpy** does.

**Comment by Yunuuuu** [comment]
Thanks for the link of [scranpy](https://github.com/biocpy/scranpy), I'll try to understand the codes of scranpy. It is delightful to learn that scran.chan will be available on Bioconductor.

**Comment by LTLA** [comment]
Closing this, but I'll note that [**scrapper**](https://bioconductor.org/packages/scrapper) is now available on BioC-release.
